"""Feature: Authorization, Change: status of user acceptance

Revision ID: b49571b8bc83
Revises: a7410c9f0c27
Create Date: 2026-03-30 14:18:58.334342

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49571b8bc83'
down_revision: Union[str, Sequence[str], None] = 'a7410c9f0c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
